#ifndef CSCRATCH_SDL_SCANCODES_H
#define CSCRATCH_SDL_SCANCODES_H

#include "include_sdl.h"
#include <cstdint>
#include <cwchar>
#include <string>
#include "string.h"
#include "runtime/math/common.h"


struct KeyData {
    const wchar_t *name;
    uint16_t scancode;
};


class ScanCodesMap {
protected:
    static constexpr uint32_t asso_values[] = {
        1294, 1294, 1294, 1294, 1294, 1294, 1294, 1294, 1294, 1294,
        1294, 1294, 1294, 1294, 1294, 1294, 1294, 1294, 1294, 1294,
        1294, 1294, 1294, 1294, 1294, 1294, 1294, 1294, 1294, 1294,
        1294, 1294, 30, 5, 1294, 440, 1294, 245, 20, 455,
        220, 155, 210, 0, 430, 165, 420, 410, 150, 140,
        130, 190, 235, 195, 265, 295, 350, 365, 15, 450,
        160, 385, 85, 1294, 75, 105, 180, 80, 320, 240,
        185, 445, 355, 175, 425, 5, 360, 25, 380, 275,
        280, 415, 270, 250, 435, 305, 370, 330, 215, 405,
        400, 395, 390, 375, 50, 1294, 345, 90, 255, 65,
        110, 10, 260, 285, 145, 160, 125, 0, 30, 20,
        135, 120, 100, 210, 60, 95, 55, 75, 340, 325,
        315, 85, 15, 35, 25, 30, 1294, 1294, 1294, 1294,
        1294, 1294, 1294, 1294, 1294, 1294, 1294, 1294, 1294, 1294,
        1294, 1294, 1294, 1294, 1294, 1294, 1294, 1294, 1294, 1294,
        1294, 1294, 1294, 1294, 1294, 1294, 1294, 1294, 1294, 1294,
        1294, 1294, 1294, 1294, 1294, 1294, 1294, 1294, 1294, 1294,
        1294, 1294, 1294, 1294, 1294, 1294, 1294, 1294, 1294, 1294,
        1294, 1294, 1294, 1294, 1294, 1294, 1294, 1294, 1294, 1294,
        1294, 1294, 1294, 1294, 1294, 1294, 1294, 1294, 1294, 1294,
        1294, 1294, 1294, 1294, 1294, 1294, 1294, 1294, 1294, 1294,
        1294, 1294, 1294, 1294, 1294, 1294, 1294, 1294, 1294, 1294,
        1294, 1294, 1294, 1294, 1294, 1294, 1294, 1294, 1294, 1294,
        1294, 1294, 1294, 1294, 1294, 1294, 1294, 1294, 1294, 1294,
        1294, 1294, 1294, 1294, 1294, 1294, 1294, 1294, 1294, 1294,
        1294, 1294, 1294, 1294, 1294, 1294, 1294
    };

    static constexpr KeyData wordList[] = {
        {L""},
        {L"k", SDL_SCANCODE_K},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L"K", SDL_SCANCODE_K},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L"e", SDL_SCANCODE_E},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L"z", SDL_SCANCODE_Z},
        {L""},
        {L"keypad +", SDL_SCANCODE_KP_PLUS},
        {L""},
        {L""},
        {L""},
        {L""},
        {L"Keypad +", SDL_SCANCODE_KP_PLUS},
        {L""},
        {L""},
        {L"m", SDL_SCANCODE_M},
        {L""},
        {L"keypad !", SDL_SCANCODE_KP_EXCLAM},
        {L""},
        {L""},
        {L""},
        {L""},
        {L"Keypad !", SDL_SCANCODE_KP_EXCLAM},
        {L""},
        {L""},
        {L"M", SDL_SCANCODE_M},
        {L""},
        {L"keypad e", SDL_SCANCODE_KP_E},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L"l", SDL_SCANCODE_L},
        {L""},
        {L"keypad :", SDL_SCANCODE_KP_COLON},
        {L""},
        {L""},
        {L""},
        {L""},
        {L"Keypad :", SDL_SCANCODE_KP_COLON},
        {L""},
        {L"keypad memstore", SDL_SCANCODE_KP_MEMSTORE},
        {L"keypad memdivide", SDL_SCANCODE_KP_MEMDIVIDE},
        {L""},
        {L"keypad &", SDL_SCANCODE_KP_AMPERSAND},
        {L"keypad &&", SDL_SCANCODE_KP_DBLAMPERSAND},
        {L""},
        {L""},
        {L""},
        {L"Keypad &", SDL_SCANCODE_KP_AMPERSAND},
        {L"Keypad &&", SDL_SCANCODE_KP_DBLAMPERSAND},
        {L"Keypad MemStore", SDL_SCANCODE_KP_MEMSTORE},
        {L"Keypad MemDivide", SDL_SCANCODE_KP_MEMDIVIDE},
        {L""},
        {L"keypad |", SDL_SCANCODE_KP_VERTICALBAR},
        {L""},
        {L"keypad | |", SDL_SCANCODE_KP_DBLVERTICALBAR},
        {L""},
        {L""},
        {L"Keypad |", SDL_SCANCODE_KP_VERTICALBAR},
        {L""},
        {L"Keypad | |", SDL_SCANCODE_KP_DBLVERTICALBAR},
        {L"keypad memrecall", SDL_SCANCODE_KP_MEMRECALL},
        {L""},
        {L"keypad }", SDL_SCANCODE_KP_RIGHTBRACE},
        {L""},
        {L""},
        {L""},
        {L""},
        {L"Keypad }", SDL_SCANCODE_KP_RIGHTBRACE},
        {L""},
        {L""},
        {L"Keypad MemRecall", SDL_SCANCODE_KP_MEMRECALL},
        {L""},
        {L"keypad {", SDL_SCANCODE_KP_LEFTBRACE},
        {L""},
        {L""},
        {L""},
        {L"keypad enter", SDL_SCANCODE_KP_ENTER},
        {L"Keypad {", SDL_SCANCODE_KP_LEFTBRACE},
        {L""},
        {L""},
        {L"t", SDL_SCANCODE_T},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L"keypad memsubtract", SDL_SCANCODE_KP_MEMSUBTRACT},
        {L""},
        {L"keypad memclear", SDL_SCANCODE_KP_MEMCLEAR},
        {L"r", SDL_SCANCODE_R},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L"Keypad MemSubtract", SDL_SCANCODE_KP_MEMSUBTRACT},
        {L""},
        {L"Keypad MemClear", SDL_SCANCODE_KP_MEMCLEAR},
        {L"c", SDL_SCANCODE_C},
        {L""},
        {L"keypad ^", SDL_SCANCODE_KP_POWER},
        {L""},
        {L""},
        {L"mediaselect", SDL_SCANCODE_MEDIASELECT},
        {L""},
        {L"Keypad ^", SDL_SCANCODE_KP_POWER},
        {L""},
        {L""},
        {L"MediaSelect", SDL_SCANCODE_MEDIASELECT},
        {L"keypad space", SDL_SCANCODE_KP_SPACE},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L"keypad memmultiply", SDL_SCANCODE_KP_MEMMULTIPLY},
        {L""},
        {L""},
        {L"u", SDL_SCANCODE_U},
        {L""},
        {L""},
        {L""},
        {L""},
        {L"delete", SDL_SCANCODE_DELETE},
        {L""},
        {L"Keypad MemMultiply", SDL_SCANCODE_KP_MEMMULTIPLY},
        {L""},
        {L""},
        {L"C", SDL_SCANCODE_C},
        {L"keypad clear", SDL_SCANCODE_KP_CLEAR},
        {L"keypad c", SDL_SCANCODE_KP_C},
        {L""},
        {L""},
        {L""},
        {L"ac back", SDL_SCANCODE_AC_BACK},
        {L"keypad memadd", SDL_SCANCODE_KP_MEMADD},
        {L""},
        {L""},
        {L"y", SDL_SCANCODE_Y},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L"ac home", SDL_SCANCODE_AC_HOME},
        {L"Keypad MemAdd", SDL_SCANCODE_KP_MEMADD},
        {L"keypad decimal", SDL_SCANCODE_KP_DECIMAL},
        {L""},
        {L"a", SDL_SCANCODE_A},
        {L"Keypad Clear", SDL_SCANCODE_KP_CLEAR},
        {L"keypad @", SDL_SCANCODE_KP_AT},
        {L"mute", SDL_SCANCODE_MUTE},
        {L""},
        {L"select", SDL_SCANCODE_SELECT},
        {L"keypad octal", SDL_SCANCODE_KP_OCTAL},
        {L"Keypad @", SDL_SCANCODE_KP_AT},
        {L"Mute", SDL_SCANCODE_MUTE},
        {L""},
        {L"s", SDL_SCANCODE_S},
        {L"keypad clearentry", SDL_SCANCODE_KP_CLEARENTRY},
        {L""},
        {L""},
        {L""},
        {L""},
        {L"AC Back", SDL_SCANCODE_AC_BACK},
        {L"Keypad C", SDL_SCANCODE_KP_C},
        {L""},
        {L"keypad +/-", SDL_SCANCODE_KP_PLUSMINUS},
        {L"p", SDL_SCANCODE_P},
        {L""},
        {L"keypad >", SDL_SCANCODE_KP_GREATER},
        {L""},
        {L"Keypad +/-", SDL_SCANCODE_KP_PLUSMINUS},
        {L""},
        {L"AC Home", SDL_SCANCODE_AC_HOME},
        {L"Keypad >", SDL_SCANCODE_KP_GREATER},
        {L""},
        {L""},
        {L"A", SDL_SCANCODE_A},
        {L"Keypad ClearEntry", SDL_SCANCODE_KP_CLEARENTRY},
        {L"keypad a", SDL_SCANCODE_KP_A},
        {L""},
        {L"crsel", SDL_SCANCODE_CRSEL},
        {L""},
        {L""},
        {L"keypad hexadecimal", SDL_SCANCODE_KP_HEXADECIMAL},
        {L""},
        {L""},
        {L"d", SDL_SCANCODE_D},
        {L""},
        {L"alterase", SDL_SCANCODE_ALTERASE},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L"menu", SDL_SCANCODE_MENU},
        {L""},
        {L"escape", SDL_SCANCODE_ESCAPE},
        {L""},
        {L""},
        {L"Menu", SDL_SCANCODE_MENU},
        {L"rctrl", SDL_SCANCODE_RCTRL},
        {L"Keypad Backspace", SDL_SCANCODE_KP_BACKSPACE},
        {L""},
        {L"AltErase", SDL_SCANCODE_ALTERASE},
        {L""},
        {L""},
        {L"o", SDL_SCANCODE_O},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L"Keypad A", SDL_SCANCODE_KP_A},
        {L"audiomute", SDL_SCANCODE_AUDIOMUTE},
        {L"rCtrl", SDL_SCANCODE_RCTRL},
        {L"j", SDL_SCANCODE_J},
        {L""},
        {L"keypad d", SDL_SCANCODE_KP_D},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L"paste", SDL_SCANCODE_PASTE},
        {L"2", SDL_SCANCODE_2},
        {L""},
        {L""},
        {L"AudioMute", SDL_SCANCODE_AUDIOMUTE},
        {L""},
        {L""},
        {L"ac stop", SDL_SCANCODE_AC_STOP},
        {L"end", SDL_SCANCODE_END},
        {L"mail", SDL_SCANCODE_MAIL},
        {L""},
        {L"n", SDL_SCANCODE_N},
        {L""},
        {L"cut", SDL_SCANCODE_CUT},
        {L"Mail", SDL_SCANCODE_MAIL},
        {L""},
        {L""},
        {L"up", SDL_SCANCODE_UP},
        {L""},
        {L"help", SDL_SCANCODE_HELP},
        {L""},
        {L"1", SDL_SCANCODE_1},
        {L"return2", SDL_SCANCODE_RETURN2},
        {L""},
        {L""},
        {L""},
        {L"return", SDL_SCANCODE_RETURN},
        {L"ac bookmarks", SDL_SCANCODE_AC_BOOKMARKS},
        {L"Cut", SDL_SCANCODE_CUT},
        {L""},
        {L""},
        {L"h", SDL_SCANCODE_H},
        {L""},
        {L"keypad 2", SDL_SCANCODE_KP_2},
        {L""},
        {L""},
        {L""},
        {L"AC Stop", SDL_SCANCODE_AC_STOP},
        {L"Keypad 2", SDL_SCANCODE_KP_2},
        {L""},
        {L"calculator", SDL_SCANCODE_CALCULATOR},
        {L"0", SDL_SCANCODE_0},
        {L"Keypad Space", SDL_SCANCODE_KP_SPACE},
        {L""},
        {L""},
        {L""},
        {L"keypad backspace", SDL_SCANCODE_KP_BACKSPACE},
        {L""},
        {L"Keypad Binary", SDL_SCANCODE_KP_BINARY},
        {L"kbdillumtoggle", SDL_SCANCODE_KBDILLUMTOGGLE},
        {L""},
        {L"cancel", SDL_SCANCODE_CANCEL},
        {L""},
        {L"keypad 1", SDL_SCANCODE_KP_1},
        {L""},
        {L"Calculator", SDL_SCANCODE_CALCULATOR},
        {L""},
        {L"AC Bookmarks", SDL_SCANCODE_AC_BOOKMARKS},
        {L"Keypad 1", SDL_SCANCODE_KP_1},
        {L""},
        {L""},
        {L"i", SDL_SCANCODE_I},
        {L""},
        {L""},
        {L""},
        {L"ac refresh", SDL_SCANCODE_AC_REFRESH},
        {L"Cancel", SDL_SCANCODE_CANCEL},
        {L""},
        {L"out", SDL_SCANCODE_OUT},
        {L""},
        {L""},
        {L"-", SDL_SCANCODE_MINUS},
        {L""},
        {L"keypad 0", SDL_SCANCODE_KP_0},
        {L"keypad 00", SDL_SCANCODE_KP_00},
        {L"keypad 000", SDL_SCANCODE_KP_000},
        {L""},
        {L""},
        {L"Keypad 0", SDL_SCANCODE_KP_0},
        {L"Keypad 00", SDL_SCANCODE_KP_00},
        {L"Keypad 000", SDL_SCANCODE_KP_000},
        {L"Select", SDL_SCANCODE_SELECT},
        {L"Keypad Enter", SDL_SCANCODE_KP_ENTER},
        {L"keypad )", SDL_SCANCODE_KP_RIGHTPAREN},
        {L"undo", SDL_SCANCODE_UNDO},
        {L"keypad tab", SDL_SCANCODE_KP_TAB},
        {L""},
        {L"Keypad Octal", SDL_SCANCODE_KP_OCTAL},
        {L"Keypad )", SDL_SCANCODE_KP_RIGHTPAREN},
        {L""},
        {L"prior", SDL_SCANCODE_PRIOR},
        {L"I", SDL_SCANCODE_I},
        {L"numlock", SDL_SCANCODE_NUMLOCKCLEAR},
        {L"keypad <", SDL_SCANCODE_KP_LESS},
        {L"stop", SDL_SCANCODE_STOP},
        {L"AC Refresh", SDL_SCANCODE_AC_REFRESH},
        {L""},
        {L""},
        {L"Keypad <", SDL_SCANCODE_KP_LESS},
        {L"audioplay", SDL_SCANCODE_AUDIOPLAY},
        {L"modeswitch", SDL_SCANCODE_MODE},
        {L"B", SDL_SCANCODE_B},
        {L""},
        {L"keypad -", SDL_SCANCODE_KP_MINUS},
        {L""},
        {L"ModeSwitch", SDL_SCANCODE_MODE},
        {L"Delete", SDL_SCANCODE_DELETE},
        {L""},
        {L"Keypad -", SDL_SCANCODE_KP_MINUS},
        {L""},
        {L"ac forward", SDL_SCANCODE_AC_FORWARD},
        {L"F", SDL_SCANCODE_F},
        {L""},
        {L"capslock", SDL_SCANCODE_CAPSLOCK},
        {L"AudioPlay", SDL_SCANCODE_AUDIOPLAY},
        {L""},
        {L""},
        {L""},
        {L"keypad binary", SDL_SCANCODE_KP_BINARY},
        {L"ac search", SDL_SCANCODE_AC_SEARCH},
        {L""},
        {L"3", SDL_SCANCODE_3},
        {L""},
        {L""},
        {L"left", SDL_SCANCODE_LEFT},
        {L"scrolllock", SDL_SCANCODE_SCROLLLOCK},
        {L""},
        {L"currencyunit", SDL_SCANCODE_CURRENCYUNIT},
        {L"CapsLock", SDL_SCANCODE_CAPSLOCK},
        {L""},
        {L"currencysubunit", SDL_SCANCODE_CURRENCYSUBUNIT},
        {L"5", SDL_SCANCODE_5},
        {L""},
        {L""},
        {L"Keypad Decimal", SDL_SCANCODE_KP_DECIMAL},
        {L"kbdillumup", SDL_SCANCODE_KBDILLUMUP},
        {L""},
        {L""},
        {L"Keypad B", SDL_SCANCODE_KP_B},
        {L""},
        {L"AC Forward", SDL_SCANCODE_AC_FORWARD},
        {L"decimalseparator", SDL_SCANCODE_DECIMALSEPARATOR},
        {L"CurrencyUnit", SDL_SCANCODE_CURRENCYUNIT},
        {L""},
        {L"audiostop", SDL_SCANCODE_AUDIOSTOP},
        {L"CurrencySubUnit", SDL_SCANCODE_CURRENCYSUBUNIT},
        {L""},
        {L""},
        {L"Keypad F", SDL_SCANCODE_KP_F},
        {L"AC Search", SDL_SCANCODE_AC_SEARCH},
        {L"keypad xor", SDL_SCANCODE_KP_XOR},
        {L"insert", SDL_SCANCODE_INSERT},
        {L""},
        {L"keypad 3", SDL_SCANCODE_KP_3},
        {L"home", SDL_SCANCODE_HOME},
        {L"exsel", SDL_SCANCODE_EXSEL},
        {L""},
        {L""},
        {L"Keypad 3", SDL_SCANCODE_KP_3},
        {L"AudioStop", SDL_SCANCODE_AUDIOSTOP},
        {L"clear", SDL_SCANCODE_CLEAR},
        {L"q", SDL_SCANCODE_Q},
        {L""},
        {L"keypad 5", SDL_SCANCODE_KP_5},
        {L"left ctrl", SDL_SCANCODE_LCTRL},
        {L"right", SDL_SCANCODE_RIGHT},
        {L"Insert", SDL_SCANCODE_INSERT},
        {L""},
        {L"Keypad 5", SDL_SCANCODE_KP_5},
        {L""},
        {L""},
        {L"X", SDL_SCANCODE_X},
        {L"kbdillumdown", SDL_SCANCODE_KBDILLUMDOWN},
        {L"Keypad Hexadecimal", SDL_SCANCODE_KP_HEXADECIMAL},
        {L""},
        {L"Clear", SDL_SCANCODE_CLEAR},
        {L""},
        {L""},
        {L""},
        {L""},
        {L"Paste", SDL_SCANCODE_PASTE},
        {L"pageup", SDL_SCANCODE_PAGEUP},
        {L""},
        {L"left alt", SDL_SCANCODE_LALT},
        {L""},
        {L""},
        {L""},
        {L"F2", SDL_SCANCODE_F2},
        {L"computer", SDL_SCANCODE_COMPUTER},
        {L""},
        {L""},
        {L"sysreq", SDL_SCANCODE_SYSREQ},
        {L""},
        {L"keypad *", SDL_SCANCODE_KP_MULTIPLY},
        {L""},
        {L"eject", SDL_SCANCODE_EJECT},
        {L""},
        {L""},
        {L"Keypad *", SDL_SCANCODE_KP_MULTIPLY},
        {L"right alt", SDL_SCANCODE_RALT},
        {L"right ctrl", SDL_SCANCODE_RCTRL},
        {L"Escape", SDL_SCANCODE_ESCAPE},
        {L""},
        {L"Computer", SDL_SCANCODE_COMPUTER},
        {L"Backspace", SDL_SCANCODE_BACKSPACE},
        {L"space", SDL_SCANCODE_SPACE},
        {L""},
        {L"F1", SDL_SCANCODE_F1},
        {L"tab", SDL_SCANCODE_TAB},
        {L"KBDIllumToggle", SDL_SCANCODE_KBDILLUMTOGGLE},
        {L""},
        {L"4", SDL_SCANCODE_4},
        {L""},
        {L"keypad (", SDL_SCANCODE_KP_LEFTPAREN},
        {L""},
        {L""},
        {L""},
        {L""},
        {L"Keypad (", SDL_SCANCODE_KP_LEFTPAREN},
        {L""},
        {L""},
        {L"E", SDL_SCANCODE_E},
        {L""},
        {L"Out", SDL_SCANCODE_OUT},
        {L"copy", SDL_SCANCODE_COPY},
        {L""},
        {L""},
        {L"BrightnessUp", SDL_SCANCODE_BRIGHTNESSUP},
        {L"thousandsseparator", SDL_SCANCODE_THOUSANDSSEPARATOR},
        {L"Help", SDL_SCANCODE_HELP},
        {L"sleep", SDL_SCANCODE_SLEEP},
        {L"printscreen", SDL_SCANCODE_PRINTSCREEN},
        {L"Return2", SDL_SCANCODE_RETURN2},
        {L""},
        {L""},
        {L""},
        {L"Return", SDL_SCANCODE_RETURN},
        {L""},
        {L"End", SDL_SCANCODE_END},
        {L"Copy", SDL_SCANCODE_COPY},
        {L""},
        {L"S", SDL_SCANCODE_S},
        {L""},
        {L"keypad 4", SDL_SCANCODE_KP_4},
        {L"separator", SDL_SCANCODE_SEPARATOR},
        {L""},
        {L""},
        {L"Up", SDL_SCANCODE_UP},
        {L"Keypad 4", SDL_SCANCODE_KP_4},
        {L"Stop", SDL_SCANCODE_STOP},
        {L""},
        {L"b", SDL_SCANCODE_B},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L"Keypad E", SDL_SCANCODE_KP_E},
        {L""},
        {L""},
        {L"f", SDL_SCANCODE_F},
        {L"f2", SDL_SCANCODE_F2},
        {L"keypad %", SDL_SCANCODE_KP_PERCENT},
        {L"BrightnessDown", SDL_SCANCODE_BRIGHTNESSDOWN},
        {L"Keypad XOR", SDL_SCANCODE_KP_XOR},
        {L""},
        {L""},
        {L"Keypad %", SDL_SCANCODE_KP_PERCENT},
        {L""},
        {L"Prior", SDL_SCANCODE_PRIOR},
        {L"6", SDL_SCANCODE_6},
        {L""},
        {L"clear / again", SDL_SCANCODE_CLEARAGAIN},
        {L"audioprev", SDL_SCANCODE_AUDIOPREV},
        {L""},
        {L""},
        {L""},
        {L""},
        {L"backspace", SDL_SCANCODE_BACKSPACE},
        {L"ScrollLock", SDL_SCANCODE_SCROLLLOCK},
        {L"R", SDL_SCANCODE_R},
        {L"f1", SDL_SCANCODE_F1},
        {L"keypad b", SDL_SCANCODE_KP_B},
        {L"oper", SDL_SCANCODE_OPER},
        {L"pause", SDL_SCANCODE_PAUSE},
        {L""},
        {L""},
        {L"Clear / Again", SDL_SCANCODE_CLEARAGAIN},
        {L"AudioPrev", SDL_SCANCODE_AUDIOPREV},
        {L"left shift", SDL_SCANCODE_LSHIFT},
        {L"O", SDL_SCANCODE_O},
        {L""},
        {L"keypad f", SDL_SCANCODE_KP_F},
        {L"audionext", SDL_SCANCODE_AUDIONEXT},
        {L"KBDIllumUp", SDL_SCANCODE_KBDILLUMUP},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L"P", SDL_SCANCODE_P},
        {L"brightnessup", SDL_SCANCODE_BRIGHTNESSUP},
        {L"keypad 6", SDL_SCANCODE_KP_6},
        {L""},
        {L""},
        {L""},
        {L"F3", SDL_SCANCODE_F3},
        {L"Keypad 6", SDL_SCANCODE_KP_6},
        {L"AudioNext", SDL_SCANCODE_AUDIONEXT},
        {L""},
        {L"g", SDL_SCANCODE_G},
        {L""},
        {L""},
        {L"Undo", SDL_SCANCODE_UNDO},
        {L""},
        {L"right shift", SDL_SCANCODE_RSHIFT},
        {L"F5", SDL_SCANCODE_F5},
        {L"displayswitch", SDL_SCANCODE_DISPLAYSWITCH},
        {L"Find", SDL_SCANCODE_FIND},
        {L""},
        {L"keypad = (as400)", SDL_SCANCODE_KP_EQUALSAS400},
        {L""},
        {L""},
        {L""},
        {L""},
        {L"Keypad = (AS400)", SDL_SCANCODE_KP_EQUALSAS400},
        {L""},
        {L"F21", SDL_SCANCODE_F21},
        {L""},
        {L""},
        {L"7", SDL_SCANCODE_7},
        {L"KBDIllumDown", SDL_SCANCODE_KBDILLUMDOWN},
        {L""},
        {L""},
        {L""},
        {L""},
        {L"Numlock", SDL_SCANCODE_NUMLOCKCLEAR},
        {L"F11", SDL_SCANCODE_F11},
        {L"brightnessdown", SDL_SCANCODE_BRIGHTNESSDOWN},
        {L"power", SDL_SCANCODE_POWER},
        {L"application", SDL_SCANCODE_APPLICATION},
        {L"execute", SDL_SCANCODE_EXECUTE},
        {L""},
        {L""},
        {L""},
        {L"SysReq", SDL_SCANCODE_SYSREQ},
        {L""},
        {L"F20", SDL_SCANCODE_F20},
        {L"right gui", SDL_SCANCODE_RGUI},
        {L"CrSel", SDL_SCANCODE_CRSEL},
        {L"U", SDL_SCANCODE_U},
        {L""},
        {L"pagedown", SDL_SCANCODE_PAGEDOWN},
        {L""},
        {L""},
        {L"Application", SDL_SCANCODE_APPLICATION},
        {L""},
        {L"F10", SDL_SCANCODE_F10},
        {L""},
        {L"Space", SDL_SCANCODE_SPACE},
        {L"PageUp", SDL_SCANCODE_PAGEUP},
        {L""},
        {L"keypad 7", SDL_SCANCODE_KP_7},
        {L"Home", SDL_SCANCODE_HOME},
        {L""},
        {L""},
        {L""},
        {L"Keypad 7", SDL_SCANCODE_KP_7},
        {L""},
        {L""},
        {L"x", SDL_SCANCODE_X},
        {L""},
        {L""},
        {L""},
        {L"Right", SDL_SCANCODE_RIGHT},
        {L""},
        {L""},
        {L"F22", SDL_SCANCODE_F22},
        {L""},
        {L""},
        {L"D", SDL_SCANCODE_D},
        {L"f3", SDL_SCANCODE_F3},
        {L""},
        {L""},
        {L"Sleep", SDL_SCANCODE_SLEEP},
        {L""},
        {L""},
        {L"F12", SDL_SCANCODE_F12},
        {L""},
        {L""},
        {L"w", SDL_SCANCODE_W},
        {L"f5", SDL_SCANCODE_F5},
        {L"left gui", SDL_SCANCODE_LGUI},
        {L"find", SDL_SCANCODE_FIND},
        {L""},
        {L""},
        {L"F4", SDL_SCANCODE_F4},
        {L""},
        {L"Separator", SDL_SCANCODE_SEPARATOR},
        {L""},
        {L"W", SDL_SCANCODE_W},
        {L""},
        {L"f21", SDL_SCANCODE_F21},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L"Right Alt", SDL_SCANCODE_RALT},
        {L"Right Ctrl", SDL_SCANCODE_RCTRL},
        {L"PrintScreen", SDL_SCANCODE_PRINTSCREEN},
        {L""},
        {L"f11", SDL_SCANCODE_F11},
        {L""},
        {L""},
        {L""},
        {L""},
        {L"Keypad D", SDL_SCANCODE_KP_D},
        {L""},
        {L""},
        {L"v", SDL_SCANCODE_V},
        {L""},
        {L"f20", SDL_SCANCODE_F20},
        {L"down", SDL_SCANCODE_DOWN},
        {L"Eject", SDL_SCANCODE_EJECT},
        {L""},
        {L""},
        {L"volumeup", SDL_SCANCODE_VOLUMEUP},
        {L""},
        {L""},
        {L"`", SDL_SCANCODE_GRAVE},
        {L""},
        {L"f10", SDL_SCANCODE_F10},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L"Oper", SDL_SCANCODE_OPER},
        {L""},
        {L"8", SDL_SCANCODE_8},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L"F19", SDL_SCANCODE_F19},
        {L""},
        {L""},
        {L"H", SDL_SCANCODE_H},
        {L""},
        {L"f22", SDL_SCANCODE_F22},
        {L"Left", SDL_SCANCODE_LEFT},
        {L""},
        {L""},
        {L"F6", SDL_SCANCODE_F6},
        {L"VolumeUp", SDL_SCANCODE_VOLUMEUP},
        {L""},
        {L""},
        {L"L", SDL_SCANCODE_L},
        {L""},
        {L"f12", SDL_SCANCODE_F12},
        {L""},
        {L"Pause", SDL_SCANCODE_PAUSE},
        {L""},
        {L""},
        {L""},
        {L""},
        {L"Keypad Tab", SDL_SCANCODE_KP_TAB},
        {L"9", SDL_SCANCODE_9},
        {L"f4", SDL_SCANCODE_F4},
        {L"keypad 8", SDL_SCANCODE_KP_8},
        {L""},
        {L""},
        {L""},
        {L""},
        {L"Keypad 8", SDL_SCANCODE_KP_8},
        {L""},
        {L""},
        {L"V", SDL_SCANCODE_V},
        {L""},
        {L"F23", SDL_SCANCODE_F23},
        {L""},
        {L"volumedown", SDL_SCANCODE_VOLUMEDOWN},
        {L""},
        {L""},
        {L"F24", SDL_SCANCODE_F24},
        {L""},
        {L""},
        {L"]", SDL_SCANCODE_RIGHTBRACKET},
        {L""},
        {L"F13", SDL_SCANCODE_F13},
        {L"Left Ctrl", SDL_SCANCODE_LCTRL},
        {L""},
        {L""},
        {L""},
        {L"F14", SDL_SCANCODE_F14},
        {L""},
        {L""},
        {L"N", SDL_SCANCODE_N},
        {L""},
        {L"keypad 9", SDL_SCANCODE_KP_9},
        {L""},
        {L""},
        {L"DecimalSeparator", SDL_SCANCODE_DECIMALSEPARATOR},
        {L""},
        {L"Keypad 9", SDL_SCANCODE_KP_9},
        {L""},
        {L"again", SDL_SCANCODE_AGAIN},
        {L"=", SDL_SCANCODE_EQUALS},
        {L""},
        {L"Left Alt", SDL_SCANCODE_LALT},
        {L""},
        {L"VolumeDown", SDL_SCANCODE_VOLUMEDOWN},
        {L""},
        {L"F7", SDL_SCANCODE_F7},
        {L""},
        {L""},
        {L"Power", SDL_SCANCODE_POWER},
        {L"\\", SDL_SCANCODE_BACKSLASH},
        {L""},
        {L"f19", SDL_SCANCODE_F19},
        {L""},
        {L"Again", SDL_SCANCODE_AGAIN},
        {L"Right Shift", SDL_SCANCODE_RSHIFT},
        {L""},
        {L"F15", SDL_SCANCODE_F15},
        {L""},
        {L""},
        {L"[", SDL_SCANCODE_LEFTBRACKET},
        {L"f6", SDL_SCANCODE_F6},
        {L"PageDown", SDL_SCANCODE_PAGEDOWN},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L"Z", SDL_SCANCODE_Z},
        {L""},
        {L"keypad =", SDL_SCANCODE_KP_EQUALS},
        {L""},
        {L""},
        {L""},
        {L""},
        {L"Keypad =", SDL_SCANCODE_KP_EQUALS},
        {L""},
        {L""},
        {L"Y", SDL_SCANCODE_Y},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L"f23", SDL_SCANCODE_F23},
        {L""},
        {L""},
        {L"/", SDL_SCANCODE_SLASH},
        {L""},
        {L"f24", SDL_SCANCODE_F24},
        {L""},
        {L""},
        {L""},
        {L""},
        {L"f13", SDL_SCANCODE_F13},
        {L""},
        {L""},
        {L"Q", SDL_SCANCODE_Q},
        {L"Execute", SDL_SCANCODE_EXECUTE},
        {L"f14", SDL_SCANCODE_F14},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L".", SDL_SCANCODE_PERIOD},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L"Tab", SDL_SCANCODE_TAB},
        {L""},
        {L""},
        {L"J", SDL_SCANCODE_J},
        {L"f7", SDL_SCANCODE_F7},
        {L"keypad /", SDL_SCANCODE_KP_DIVIDE},
        {L""},
        {L""},
        {L""},
        {L""},
        {L"Keypad /", SDL_SCANCODE_KP_DIVIDE},
        {L""},
        {L""},
        {L",", SDL_SCANCODE_COMMA},
        {L""},
        {L"f15", SDL_SCANCODE_F15},
        {L""},
        {L""},
        {L""},
        {L""},
        {L"ThousandsSeparator", SDL_SCANCODE_THOUSANDSSEPARATOR},
        {L""},
        {L""},
        {L"T", SDL_SCANCODE_T},
        {L""},
        {L"keypad .", SDL_SCANCODE_KP_PERIOD},
        {L""},
        {L""},
        {L""},
        {L""},
        {L"Keypad .", SDL_SCANCODE_KP_PERIOD},
        {L""},
        {L"Left Shift", SDL_SCANCODE_LSHIFT},
        {L"#", SDL_SCANCODE_NONUSHASH},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L"F8", SDL_SCANCODE_F8},
        {L"F16", SDL_SCANCODE_F16},
        {L""},
        {L""},
        {L"G", SDL_SCANCODE_G},
        {L""},
        {L"keypad ,", SDL_SCANCODE_KP_COMMA},
        {L"Down", SDL_SCANCODE_DOWN},
        {L""},
        {L""},
        {L""},
        {L"Keypad ,", SDL_SCANCODE_KP_COMMA},
        {L""},
        {L""},
        {L";", SDL_SCANCODE_SEMICOLON},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L"'", SDL_SCANCODE_APOSTROPHE},
        {L""},
        {L"keypad #", SDL_SCANCODE_KP_HASH},
        {L""},
        {L""},
        {L""},
        {L"F9", SDL_SCANCODE_F9},
        {L"Keypad #", SDL_SCANCODE_KP_HASH},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L"DisplaySwitch", SDL_SCANCODE_DISPLAYSWITCH},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L"f8", SDL_SCANCODE_F8},
        {L"f16", SDL_SCANCODE_F16},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L"F17", SDL_SCANCODE_F17},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L"f9", SDL_SCANCODE_F9},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L"Left GUI", SDL_SCANCODE_LGUI},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L"ExSel", SDL_SCANCODE_EXSEL},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L"F18", SDL_SCANCODE_F18},
        {L""},
        {L""},
        {L""},
        {L""},
        {L"f17", SDL_SCANCODE_F17},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L"Right GUI", SDL_SCANCODE_RGUI},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L"f18", SDL_SCANCODE_F18},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L"WWW", SDL_SCANCODE_WWW},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L""},
        {L"www", SDL_SCANCODE_WWW}
    };

    static constexpr uint32_t hash(const wchar_t *str, uint64_t len) {
        uint32_t hval = len;

        switch (hval) {
        default:
            hval += asso_values[static_cast<uint32_t>(str[7])];
        /*FALLTHROUGH*/
        case 7:
        case 6:
        case 5:
        case 4:
        case 3:
            hval += asso_values[static_cast<uint32_t>(str[2] + 1)];
        /*FALLTHROUGH*/
        case 2:
            hval += asso_values[static_cast<uint32_t>(str[1])];
        /*FALLTHROUGH*/
        case 1:
            hval += asso_values[static_cast<uint32_t>(str[0])];
            break;
        }
        return hval + asso_values[static_cast<uint32_t>(str[len - 1])];
    }

public:
    static constexpr uint64_t TOTAL_KEYWORDS = 418;
    static constexpr uint64_t MIN_WORD_LENGTH = 1;
    static constexpr uint64_t MAX_WORD_LENGTH = 18;
    static constexpr uint64_t MIN_HASH_VALUE = 1;
    static constexpr uint64_t MAX_HASH_VALUE = 1293;

    static constexpr uint16_t getScanCode(const wchar_t * str, uint64_t len) {
        if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH) {
            uint32_t key = hash(str, len);

            if (key <= MAX_HASH_VALUE) {
                const wchar_t *s = wordList[key].name;

                if (
                    *str == *s
                    && !std::char_traits<wchar_t>::compare(
                        str + 1,
                        s + 1,
                        MIN(len, std::char_traits<wchar_t>::length(s+1))
                    )
                )
                    return wordList[key].scancode;
            }
        }
        return 0;
    }

    static constexpr uint16_t getScanCode(const String &str) {
        return getScanCode(str.data, str.length);
    }
};

static constexpr uint16_t operator ""_K(const wchar_t * str, uint64_t size) {
    return ScanCodesMap::getScanCode(str, size);
}

#endif
